"""add observations table

Revision ID: 8e53531f8b72
Revises: 3c2478ac7241
Create Date: 2026-09-04 00:06:09.094141

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8e53531f8b72'
down_revision: str | Sequence[str] | None = '3c2478ac7241'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('memory_id', sa.Integer(), nullable=False),
    sa.Column('observed_form', sa.String(length=255), nullable=False),
    sa.Column('evidence_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observations')
    # ### end Alembic commands ###
