"""add candidate importance and risk

Revision ID: d3914ad4cef7
Revises: e63f359628b1
Create Date: 2026-09-05 23:30:24.249483

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd3914ad4cef7'
down_revision: str | Sequence[str] | None = 'e63f359628b1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_candidates', sa.Column('importance', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('memory_candidates', sa.Column('risk_level', sa.String(length=20), server_default='medium', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memory_candidates', 'risk_level')
    op.drop_column('memory_candidates', 'importance')
    # ### end Alembic commands ###
