"""add candidate evidence type

Revision ID: e63f359628b1
Revises: d034b72046bc
Create Date: 2026-09-05 19:00:22.171849

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e63f359628b1'
down_revision: str | Sequence[str] | None = 'd034b72046bc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'memory_candidates',
        sa.Column(
            'evidence_type',
            sa.String(length=50),
            nullable=False,
            server_default='asr_formatted_substitution',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memory_candidates', 'evidence_type')
    # ### end Alembic commands ###
